In [1]:
import numpy as np

In [9]:
# Q.1)  Create a 5x5 matrix with row values ranging from 0 to 4

a=np.zeros((5,5))
a+= np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [10]:
# Q.2) Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

b=np.arange(15).reshape(5,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [11]:
c=np.arange(6).reshape(3,2)
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [15]:
d=np.dot(b, c)
d.ndim

2

In [16]:
print(d)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [18]:
# Q.3) What is the result of the following expression?
x=0*np.nan
x

nan

In [19]:
np.nan == np.nan

False

In [20]:
np.inf > np.nan

False

In [21]:
np.nan - np.nan

nan

In [22]:
np.nan in set([np.nan])

True

In [23]:
0.3 == 3 * 0.1


False

In [37]:
# Q.4) Create a 10x10 array with random values and find the minimum and maximum values

s=np.random.random((10,10))
s

array([[0.38660064, 0.60863439, 0.89823269, 0.88753945, 0.49464345,
        0.19400641, 0.08900348, 0.29125124, 0.84296871, 0.09847795],
       [0.23061038, 0.39494451, 0.30817463, 0.34953325, 0.88379615,
        0.95664874, 0.49346275, 0.31992536, 0.76637404, 0.36001834],
       [0.62069414, 0.27573784, 0.91952684, 0.73956879, 0.81302357,
        0.17199671, 0.95083636, 0.28742371, 0.29373023, 0.66605251],
       [0.33488751, 0.68987818, 0.35414609, 0.99257218, 0.17548677,
        0.8209839 , 0.89744555, 0.54769223, 0.51666196, 0.79788365],
       [0.35519705, 0.38616445, 0.17645692, 0.8671477 , 0.99097826,
        0.96871696, 0.95707758, 0.72461095, 0.66277527, 0.68658931],
       [0.293176  , 0.14442732, 0.85543882, 0.51723393, 0.59223037,
        0.21374523, 0.02108789, 0.54629659, 0.43235656, 0.84719288],
       [0.40799589, 0.24929538, 0.6503447 , 0.76587112, 0.82770306,
        0.47233773, 0.59100288, 0.08311752, 0.37985207, 0.05322728],
       [0.06058243, 0.49382278, 0.8820846

In [31]:
smin= s.min()

In [32]:
smax=s.max()

In [33]:
smin

0.002228917186938739

In [34]:
smax

0.9942878519385894

In [41]:
# Q.5) Create a null vector of size 10 but the fifth value which is 1

k=np.zeros((10,10), dtype=int)
k

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [42]:
k[4]=1

In [43]:
k

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])