In [131]:
import numpy as np

In [132]:
# Q.1) Create an array filled with random values.

A=np.random.randint(100)
print(A)

31


In [133]:
# Q.2) I) Create rank 1 Array

B=np.array([2,5,8,10,22])
print(B)
B.ndim

[ 2  5  8 10 22]


1

In [134]:
# Q.2) II) Print"(3,)"

print"(3,)"

SyntaxError: invalid syntax (1893249865.py, line 3)

In [135]:
# Q.2) III) Print"1,2,3"

print"1,2,3"

SyntaxError: invalid syntax (908293349.py, line 3)

In [136]:
# Q.2) IV) Change an element of  the array
# B=[ 2  5  8 10 22]
B[2]=20
print(B)

[ 2  5 20 10 22]


In [137]:
# Q.2) V) Create a rank 2 array

c=np.array([[1, 2, 3], [4, 5, 6]])
print(c)
c.ndim

[[1 2 3]
 [4 5 6]]


2

In [138]:
# Q.3.1) Create an array of all ones

D= np.ones(3,  dtype=int)
print(D)

[1 1 1]


In [139]:
# Q.3.2) Create a constant array

a= np.full((3,3),5)
print(a)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [140]:
# Q.3.3) Create a 2x2 identity matrix

E=np.identity(2, dtype=int)
print(E)

[[1 0]
 [0 1]]


In [141]:
#Q.4.1) Create the following rank 2 array with shape (3, 4)
  
F=np.arange(12).reshape(3,4)
print(F)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [142]:
# Q 4.2)Use slicing to pull out the subarray consisting of 
#        the first 2 rows and columns 1 and 2; b is the following array of shape (2, 2)

F[0:2,0:4]



array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [143]:
B=F[0:2,1:3]
print(B)
B.shape

[[1 2]
 [5 6]]


(2, 2)

In [144]:
# Q.5) Q5
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
#sum, divide,product,divide,square root


In [145]:
x

array([[1., 2.],
       [3., 4.]])

In [146]:
y

array([[5., 6.],
       [7., 8.]])

In [147]:
A= x+y
print(A)

[[ 6.  8.]
 [10. 12.]]


In [148]:
B=x/y
print(B)
B.shape

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


(2, 2)

In [149]:
C=x*y
C

array([[ 5., 12.],
       [21., 32.]])

In [150]:
sqrt_x=np.sqrt(x)
sqrt_x

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [151]:
sqrt_y=np.sqrt(y)
sqrt_y

array([[2.23606798, 2.44948974],
       [2.64575131, 2.82842712]])

In [152]:
# Q.6) Q6
v = np.array([1, 0, 1])
# Stack 4 copies of v on top of each other
#Generate an array of length 3n filled with the cyclic pattern 1, 2, 3
v

array([1, 0, 1])

In [153]:
z=np.array([v,v,v], dtype=int)
z

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [154]:
z=np.vstack([v,v,v])
z

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [155]:
# Q.7)
#Create an array of the first 10 odd integers.
y=[]
x=[]

for i in range(10):
    y.append(i)
    print(y) #incremental
    if i%2==1:
        x.append(i)
x    

[0]
[0, 1]
[0, 1, 2]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 4, 5, 6]
[0, 1, 2, 3, 4, 5, 6, 7]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


[1, 3, 5, 7, 9]

In [158]:
# Find intersection of a and b  (x,y)
print(x)
print(y)
print("intersection of x & y :",intersection(x,y))

[1, 3, 5, 7, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
intersection of x & y : [1, 3, 5, 7, 9]


In [163]:
# Q.8)
##Reshape 1d array a to 2d array of 2X5
##Create a numpy array to list and vice versa

x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [174]:
x=np.array(x).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [175]:
x.ndim

2

In [182]:
g=np.arange(20)
print(g)
type(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


numpy.ndarray

In [184]:
g=list(g)
print(g)
type(g)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


list

In [202]:
g=np.array(g)
print(g)
type(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


numpy.ndarray

In [252]:
# Q.9)

#Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

x=np.zeros((10,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [253]:
x[0,]=1

x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [254]:
x[:,-1]=1
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [255]:
x[:,0]=1
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [256]:
x[-1,:]=1
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [261]:
#Q.10)
# Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

z=np.zeros((8,8))
z

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [262]:
z[1::2,::2] = 1

print(z)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [264]:
z[::2,1::2] = 1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
